### PR TITLE
Make use of ipl/orm

### LINKED ISSUE #142: Random ordering in certificate dashboard
## Describe the bug
Reloading the certificate dashboard multiple times results in random ordering of the elements.

## To Reproduce

1. Hit reload multiple times

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.2
* x509 Version: 1.1.2
* PHP Version: PHP 7.4.3

### PR DESCRIPTION
**Pull request by yhabteab**
fixes #142, #143

### CODE REVIEW

**Comment by yhabteab** [comment]
### Blocked by
- https://github.com/Icinga/ipl-orm/pull/81

**Comment by yhabteab** [comment]
### Tests

**CLI:**

```php
root@29b932b60d5f:/# icingacli x509 check --ip 10.211.55.31 --port 443
OK - Icinga Web 2 expires in 366 days|'Icinga Web 2'=31622836s;8553600:;3456000:;0;34214400
root@29b932b60d5f:/# icingacli x509 check --ip 10.211.55.31 --port 5665
OK - docker-master expires in 390 days|'docker-master'=33723335s;8557200:;3459600:;0;34300800
root@29b932b60d5f:/# icingacli x509 check --ip 10.211.55.31 --port 6379
OK - Icinga DB Redis expires in 366 days|'Icinga DB Redis'=31623859s;8553600:;3456000:;0;34214400
```

**Director hooks 🪝:**
Bildschirmfoto 2022-10-20 um 10 10 12

**Certificate Usages:**
Bildschirmfoto 2022-10-20 um 10 12 04

**Host Details:**
Bildschirmfoto 2022-10-20 um 10 13 32

**Certificate Overview:**
Bildschirmfoto 2022-10-20 um 10 15 17

**Certificate Details:**
Bildschirmfoto 2022-10-20 um 10 16 21

**Review by lippserd — CHANGES_REQUESTED** [review]
I think you can also remove the class `SqlFilter` and fix #142.

**Comment by yhabteab** [comment]
Filtering something like this `icingaweb2/x509/certificates?duration=34300800&ca=n` doesn't work anymore with the new bool cast behaviour.

```php
Expected bool, got string instead

#0 /usr/local/src/ipl-orm/src/Contract/PropertyBehavior.php(80): ipl\Orm\Behavior\BoolCast->toDb(String, String, Integer)
#1 /usr/local/src/ipl-orm/src/Behaviors.php(137): ipl\Orm\Contract\PropertyBehavior->persistProperty(String, String)
#2 /usr/local/src/ipl-orm/src/Compat/FilterProcessor.php(115): ipl\Orm\Behaviors->persistProperty(String, String)
#3 /usr/local/src/ipl-orm/src/Compat/FilterProcessor.php(148): ipl\Orm\Compat\FilterProcessor->requireAndResolveFilterColumns(Object(ipl\Stdlib\Filter\Equal), Object(ipl\Orm\Query), NULL)
...
```

**Comment by yhabteab** [comment]
Bildschirm­foto 2022-11-17 um 09 54 57

File: application/controllers/ChainController.php [hunk 1]
```diff
@@ -69,17 +66,15 @@ public function indexAction()
...
         }
 
-        $certsSelect = (new Sql\Select())
-            ->from('x509_certificate c')
-            ->columns('*')
-            ->join('x509_certificate_chain_link ccl', 'ccl.certificate_id = c.id')
-            ->join('x509_certificate_chain cc', 'cc.id = ccl.certificate_chain_id')
-            ->where(['cc.id = ?' => $id])
-            ->orderBy('ccl.order');
+        $certs = X509Certificate::on($conn)->with(['chain']);
```
Comment (lippserd) [inline application/controllers/ChainController.php:69]: You could chain everything together, couldn't you?

File: application/controllers/UsageController.php [hunk 2]
```diff
@@ -32,132 +28,125 @@ public function indexAction()
...
-        $this->setupFilterControl(
-            $filterAdapter,
-            $sortAndFilterColumns,
-            ['hostname', 'subject'],
-            ['format']
-        );
-
-        (new SqlFilter($conn))->apply($select, $filterAdapter->getFilter(), function (FilterExpression $filter) {
-            switch ($filter->getColumn()) {
-                case 'ip':
```
Comment (lippserd) [inline application/controllers/UsageController.php:91]: Please introduce behavior `Ip` to make it possible to filter for specific IPs.

File: application/controllers/DashboardController.php [hunk 3]
```diff
@@ -25,15 +27,18 @@ public function indexAction()
...
-        $byCa = $db->select(
-            (new Select())
-                ->from('x509_certificate i')
-                ->columns(['i.subject', 'cnt' => 'COUNT(*)'])
-                ->join('x509_certificate c', ['c.issuer_hash = i.subject_hash', 'i.ca = ?' => 'y'])
-                ->groupBy(['i.id'])
-                ->orderBy('cnt', SORT_DESC)
-                ->limit(5)
-        );
+        $byCa = X509Certificate::on($db);
```
Comment (lippserd) [inline application/controllers/DashboardController.php:30]: Please use method chaining for such cases everywhere 😆

File: application/controllers/UsageController.php [hunk 4]
```diff
@@ -32,132 +28,125 @@ public function indexAction()
...
+        $targets->peekAhead($this->view->compact);
+
+        $targets->filter($filter);
+
+        $this->addControl($paginator);
+        $this->addControl($sortControl);
+        $this->addControl($limitControl);
+        $this->addControl($searchBar);
+
+        $exportable = array_flip([
```
Comment (lippserd) [inline application/controllers/UsageController.php:96]: What are you excluding here?

**Review by lippserd — CHANGES_REQUESTED** [review]

File: library/X509/CertificateDetails.php [hunk 5]
```diff
@@ -22,7 +23,7 @@ class CertificateDetails extends BaseHtmlElement
      */
     protected $cert;
 
-    public function setCert(array $cert)
+    public function setCert(Model $cert)
```
Comment (lippserd) [inline library/X509/CertificateDetails.php:26]: Please use the concrete model class here.

File: library/X509/Job.php [hunk 6]
```diff
@@ -433,18 +436,17 @@ protected function processChain($target, $chain)
...
-                        'port = ?'     => $target->port,
-                        'hostname = ?' => $target->hostname
-                    ])
-            )->fetch();
-
-            if ($row === false) {
+            $row = X509Target::on($this->db)->columns(['id']);
+
+            $filter = Filter::all();
+            $filter->add(Filter::equal('ip', static::binary($target->ip)));
```
Comment (lippserd) [inline library/X509/Job.php:442]: Is `::binary()` still needed?

**Review by lippserd — CHANGES_REQUESTED** [review]

File: library/X509/ProvidedHook/HostsImportSource.php [hunk 7]
```diff
@@ -56,7 +60,12 @@ public function fetchData()
                 $target->host_name_or_ip = $target->host_ip;
             }
 
-            $results[$target->host_name_or_ip] = $target;
+            unset($target->ip); // Isn't needed any more!!
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply library/X509/ProvidedHook/HostsImportSource.php:63]: The `ip' is processed just before, so it's now obsolete and we don't have to include it int the results. The same also with relations!

[the remark this answers is not in the document]
Comment (lippserd) [reply library/X509/ProvidedHook/HostsImportSource.php:63]: Your comments should reflect what you've just described please.

**Comment by lippserd** [comment]
@yhabteab Please rebase an re-request review.

File: application/controllers/CertificatesController.php [hunk 8]
```diff
@@ -4,126 +4,123 @@
...
+        $this->addContent((new CertificatesTable())->setData($certificates));
+
+        if (! $searchBar->hasBeenSubmitted() && $searchBar->hasBeenSent()) {
+            $this->sendMultipartUpdate(); // Updates the browser search bar
+        }
+    }
+
+    public function completeAction()
+    {
+        $suggestions = new ObjectSuggestions();
```
Comment (lippserd) [inline application/controllers/CertificatesController.php:110]: Can this be chained?

File: application/controllers/UsageController.php [hunk 9]
```diff
@@ -32,132 +28,118 @@ public function indexAction()
...
+            $sortControl->getSortParam()
+        ]);
+
+        if ($searchBar->hasBeenSent() && ! $searchBar->isValid()) {
+            if ($searchBar->hasBeenSubmitted()) {
+                $filter = $this->getFilter();
+            } else {
+                $this->addControl($searchBar);
+                $this->sendMultipartUpdate();
+                return;
```
Comment (lippserd) [inline application/controllers/UsageController.php:81]: Please add a newline before the `return`.

File: application/controllers/UsageController.php (hunk 4 above)
Comment (lippserd) [reply application/controllers/UsageController.php:96]: Also a candidate for the `getExportableColumns()` method.

File: application/controllers/UsageController.php [hunk 10]
```diff
@@ -32,132 +28,118 @@ public function indexAction()
...
+        $this->addContent((new UsageTable())->setData($targets));
+
+        if (! $searchBar->hasBeenSubmitted() && $searchBar->hasBeenSent()) {
+            $this->sendMultipartUpdate(); // Updates the browser search bar
+        }
+    }
+
+    public function completeAction()
+    {
+        $suggestions = new ObjectSuggestions();
```
Comment (lippserd) [inline application/controllers/UsageController.php:129]: Can this be chained?

File: library/X509/DataTable.php [hunk 11]
```diff
@@ -84,13 +84,16 @@ protected function renderRow($row)
         $cells = [];
 
         foreach ($this->columns as $key => $column) {
-            if (! is_int($key) && array_key_exists($key, $row)) {
```
Comment (lippserd) [inline library/X509/DataTable.php:87]: Since `array_key_exists` is different from `isset`, are you sure this will work as before?

File: library/X509/Job.php [hunk 12]
```diff
@@ -191,16 +194,16 @@ protected function getScanTargets(): Generator
...
             yield from $this->generateTargets();
         } else {
-            $targets = (new Select())
-                ->columns(['id', 'ip', 'hostname', 'port'])
-                ->from('x509_target');
-
+            $targets = X509Target::on($this->db)->columns(['id', 'ip', 'hostname', 'port']);
             if ($this->sinceLastScan) {
-                $targets->where(new Expression('last_scan < %d', [$this->sinceLastScan->getTimestamp()]));
+                // The filter processor doesn't allow us to filter using expressions
```
Comment (lippserd) [inline library/X509/Job.php:199]: Is this still true?

File: library/X509/Job.php [hunk 13]
```diff
@@ -433,18 +436,17 @@ protected function processChain($target, $chain)
...
-                        'ip = ?'       => $this->dbTool->marshalBinary(static::binary($target->ip)),
-                        'port = ?'     => $target->port,
-                        'hostname = ?' => $target->hostname
-                    ])
-            )->fetch();
-
-            if ($row === false) {
+            $row = X509Target::on($this->db)->columns(['id']);
+
+            $filter = Filter::all();
```
Comment (lippserd) [inline library/X509/Job.php:441]: Please chain.

File: library/X509/Job.php [hunk 14]
```diff
@@ -456,32 +458,31 @@ protected function processChain($target, $chain)
...
-
-                foreach ($lastFingerprints as &$lastFingerprint) {
-                    $lastFingerprint = $lastFingerprint->fingerprint;
+            $lastChain = X509CertificateChain::on($this->db)->columns(['id']);
+            $lastChain
+                ->filter(Filter::equal('target_id', $targetId))
+                ->orderBy('id', SORT_DESC)
+                ->limit(1);
+
+            if (($lastChain = $lastChain->first())) {
```
Comment (lippserd) [inline library/X509/Job.php:472]: No assignments in `if`s please.

File: library/X509/Job.php [hunk 15]
```diff
@@ -490,12 +491,13 @@ protected function processChain($target, $chain)
                     $currentFingerprints[] = openssl_x509_fingerprint($cert, 'sha256', true);
                 }
 
-                $chainUptodate = $currentFingerprints === $lastFingerprints;
+                $chainUptodate = $currentFingerprints === $lastFingerprintsArr;
             }
 
             if ($chainUptodate) {
-                $chainId = $lastChain->id;
+                $chainId = (int) $lastChain->id;
```
Comment (lippserd) [inline library/X509/Job.php:498]: Why the cast?

**Review by lippserd — CHANGES_REQUESTED** [review]

File: application/controllers/CertificatesController.php [hunk 16]
```diff
@@ -30,100 +27,99 @@ public function indexAction()
...
+        $exportable = array_flip([
+            'id', 'subject', 'issuer', 'version', 'self_signed', 'ca', 'trusted',
+            'pubkey_algo', 'pubkey_bits', 'signature_algo', 'signature_hash_algo',
+            'valid_from', 'valid_to'
+        ]);
+
+        $this->handleFormatRequest($certificates, function (Query $certificates) use ($exportable) {
+            /** @var X509Certificate $cert */
+            foreach ($certificates as $cert) {
                 $cert['valid_from'] = (new \DateTime())
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply application/controllers/CertificatesController.php:90]: This will be dropped with the next PR anyway, as soon as the `MillisecondTimestamp` behaviour is finished.

File: library/X509/Job.php (hunk 12 above)
Comment (yhabteab) [reply library/X509/Job.php:199]: still? After all, not much has changed since then. But yes, it is still unsupported!

File: library/X509/Job.php [hunk 17]
```diff
@@ -456,32 +458,31 @@ protected function processChain($target, $chain)
...
+                ->filter(Filter::equal('target_id', $targetId))
+                ->orderBy('id', SORT_DESC)
+                ->limit(1);
+
+            if (($lastChain = $lastChain->first())) {
+                $lastFingerprints = X509Certificate::on($this->db)->utilize('chain');
+                $lastFingerprints
+                    ->columns(['fingerprint'])
+                    ->getSelectBase()
+                    ->where(new Expression(
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply library/X509/Job.php:477]: `certificate_link` can' t be resolved at orm/filterprocessor level since it originates from a junction model used as a `through()` class.

File: application/clicommands/CheckCommand.php [hunk 18]
```diff
@@ -66,42 +67,57 @@ public function hostAction()
...
+            'chain.valid',
+            'chain.invalid_reason',
+            'subject'     => 'chain.certificate.subject',
+            'self_signed' => new Expression('COALESCE(%s, %s)', [
+                'chain.certificate.issuer_certificate.self_signed',
+                'chain.certificate.self_signed'
+            ])
+        ]);
+
+        // Sub queries for (valid_from, valid_to) columns
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply application/clicommands/CheckCommand.php:90]: I'm not sure what exactly you want different, but how do you want the ORM to natively build this for me? The only thing I could do is instead of manually creating the subqueries, replace them by `Query::createSubQuery()`. I would still have to manually assemble the subqueries before I can use them for the columns.

https://github.com/Icinga/icingadb-web/blob/master/library/Icingadb/Model/Behavior/FlattenedObjectVars.php#L45-L55

[the remark this answers is not in the document]
Comment (lippserd) [reply application/clicommands/CheckCommand.php:91]: I don't have anything specific in mind, but find it wrong to have to call `dump()`.

File: application/controllers/CertificatesController.php [hunk 19]
```diff
@@ -4,126 +4,117 @@
...
+            $limitControl->getLimitParam(),
+            $sortControl->getSortParam()
+        ]);
+
+        if ($searchBar->hasBeenSent() && ! $searchBar->isValid()) {
+            if ($searchBar->hasBeenSubmitted()) {
+                $filter = $this->getFilter();
+            } else {
+                $this->addControl($searchBar);
+                $this->sendMultipartUpdate();
```
Comment (lippserd) [inline application/controllers/CertificatesController.php:64]: Add a newline before the return please.

File: application/controllers/CertificatesController.php (hunk 16 above)
[the remark this answers is not in the document]
Comment (lippserd) [reply application/controllers/CertificatesController.php:83]: Alright.

File: library/X509/Job.php (hunk 12 above)
Comment (lippserd) [reply library/X509/Job.php:199]: And `Filter::greateThan()` does not work? Also `where(['last_scan < ?', $timestamp])` should work. I don't see the need for an expression. Anyway do we have an issue for expression support in our ORM?

File: library/X509/Job.php (hunk 17 above)
[the remark this answers is not in the document]
Comment (lippserd) [reply library/X509/Job.php:478]: I see. Can you please open an issue? Filtering for `certificate.link` should be possible.

File: library/X509/Job.php [hunk 20]
```diff
@@ -456,32 +458,32 @@ protected function processChain($target, $chain)
...
+                        'certificate_link.certificate_chain_id = %d',
+                        [(int) $lastChain->id]
+                    ))
+                    ->orderBy('certificate_link.order');
+
+                $lastFingerprintsArr = [];
```
Comment (lippserd) [inline library/X509/Job.php:484]: We have such code here and there and I think it makes sense to add a method for it in our ORM, i.e. `pluck(string ...$columns)`. Could you please open an issue for that?

**Review by lippserd — CHANGES_REQUESTED** [review]
In addition to the requested changes, please use double quotes for strings containing single quotes instead of escaping them.

File: library/X509/Job.php (hunk 17 above)
[the remark this answers is not in the document]
Comment (yhabteab) [reply library/X509/Job.php:478]: done ✅

File: library/X509/Job.php (hunk 20 above)
Comment (yhabteab) [reply library/X509/Job.php:484]: Done ✅

File: application/clicommands/CheckCommand.php (hunk 18 above)
[the remark this answers is not in the document]
Comment (yhabteab) [reply application/clicommands/CheckCommand.php:91]: I could also assemble the query manually, though, so I could just copy what `dump()` does!

[the remark this answers is not in the document]
Comment (lippserd) [reply application/clicommands/CheckCommand.php:91]: Hmm, let's leave it as it is then.

File: library/X509/Model/Behavior/ExpressionInjector.php [hunk 21]
```diff
@@ -0,0 +1,53 @@
+<?php
+
+namespace Icinga\Module\X509\Model\Behavior;
+
+use ipl\Orm\Contract\QueryAwareBehavior;
+use ipl\Orm\Contract\RewriteFilterBehavior;
+use ipl\Orm\Query;
+use ipl\Stdlib\Filter;
+
+class ExpressionInjector implements RewriteFilterBehavior, QueryAwareBehavior
```
Comment (lippserd) [inline library/X509/Model/Behavior/ExpressionInjector.php:10]: Please document what this is doing.

File: library/X509/Model/Behavior/Ip.php [hunk 22]
```diff
@@ -0,0 +1,31 @@
+<?php
+
+namespace Icinga\Module\X509\Model\Behavior;
+
+use ipl\Orm\Contract\PropertyBehavior;
+
+class Ip extends PropertyBehavior
```
Comment (lippserd) [inline library/X509/Model/Behavior/Ip.php:7]: Add documentation please.

File: library/X509/Model/Behavior/DistinguishedEncodingRules.php [hunk 23]
```diff
@@ -0,0 +1,39 @@
+<?php
+
+namespace Icinga\Module\X509\Model\Behavior;
+
+use ipl\Orm\Contract\PropertyBehavior;
+
+class DistinguishedEncodingRules extends PropertyBehavior
```
[the remark this answers is not in the document]
Comment (lippserd) [reply library/X509/Model/Behavior/DistinguishedEncodingRules.php:7]: Please add documentation.

File: application/clicommands/CheckCommand.php [hunk 24]
```diff
@@ -66,42 +68,55 @@ public function hostAction()
...
-            $targets->where(['t.ip = ?' => $dbTool->marshalBinary(Job::binary($ip))]);
+            $targets->filter(Filter::equal('ip', $ip));
         }
         if ($hostname !== null) {
-            $targets->where(['t.hostname = ?' => $hostname]);
+            $targets->filter(Filter::equal('hostname', $hostname));
         }
         if ($this->params->has('port')) {
-            $targets->where(['t.port = ?' => $this->params->get('port')]);
+            $targets->filter(Filter::equal('port', (int) $this->params->get('port')));
```
Comment (lippserd) [inline application/clicommands/CheckCommand.php:119]: Why the `(int)` cast?

File: library/X509/Job.php [hunk 25]
```diff
@@ -456,32 +455,32 @@ protected function processChain($target, $chain)
                 );
                 $targetId = $this->db->lastInsertId();
             } else {
-                $targetId = $row->id;
+                $targetId = (int) $row->id;
```
Comment (lippserd) [inline library/X509/Job.php:458]: Why the cast?

**Review by lippserd — CHANGES_REQUESTED** [review]

**Review by lippserd — APPROVED** [review]
