### PR TITLE
Separate jobs and schedule config

### LINKED ISSUE #181: Scan jobs run by daemon not updating allready scanned Targets
## Describe the bug
Scan jobs run by daemon not updating allready scanned Targets

## To Reproduce
Discover Certificates once.
Replace Certificate on target mashine with a new one.

## Expected behavior
After next Scan run the old certificate should disappear and the new one should be diplayed, with new expiration date.

## Current behavior
Old certificate is still there. The entry is not updated.
Only running icingacli x509 scan  with the--full option fixes this.

## Your Environment
Environment:
Ubuntu Server 22.02.2
Icinga Web 2 Version 2.11.4
PHP Version 8.1.2-1ubuntu2.11
MariaDB 15.1
icingadb 1.0.2
x509 1.2.1

It seems that the daemon, icingacli x509 jobs run, is not scanning already scanned hosts aggain.

Is there an intervall for this ?
Can i configure the daemon to always Scan all Hosts again ?

### PR DESCRIPTION
**Pull request by yhabteab**
fixes #181

### CODE REVIEW

File: application/clicommands/ScanCommand.php
Comment (lippserd) [inline application/clicommands/ScanCommand.php:1]: What is the motivation for changing this command?

File: library/X509/Web/Widget/EmptyList.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
+<?php
+
+// Icinga Web 2 X.509 Module | (c) 2023 Icinga GmbH | GPLv2
+
+namespace Icinga\Module\X509\Web\Widget;
+
+use ipl\Html\BaseHtmlElement;
+use ipl\Html\Text;
+
+class EmptyList extends BaseHtmlElement
```
Comment (lippserd) [inline library/X509/Web/Widget/EmptyList.php:10]: We call that `empty-state` everywhere else, e.g. https://github.com/Icinga/icingadb-web/blob/master/library/Icingadb/Widget/EmptyState.php

**Review by lippserd — CHANGES_REQUESTED** [review]

File: schema/mysql-upgrades/1.2.2.sql [hunk 2]
```diff
@@ -0,0 +1,37 @@
+CREATE TABLE IF NOT EXISTS x509_job (
+  id int(10) unsigned NOT NULL AUTO_INCREMENT,
+  name varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci,
+  author varchar(255) NOT NULL COLLATE utf8mb4_unicode_ci,
+  cidrs text NOT NULL,
+  ports text NOT NULL,
+  exclude_targets text DEFAULT NULL,
```
Comment (lippserd) [inline schema/mysql-upgrades/1.2.2.sql:7]: What about `ctime` and `mtime` for this table as well?

File: public/css/module.less [hunk 3]
```diff
@@ -6,6 +6,27 @@
 @cert-segment-color-3: #1982C4;
 @cert-segment-color-4: #6A4C93;
 
+.controls.default-layout > :not(:only-child) {
+  // Reset the margin set in ipl web!
```
Comment (lippserd) [inline public/css/module.less:10]: Why the reset? Does it make sense to transfer this to `ipl-web`?

File: library/X509/Widget/Schedules.php [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+    protected function assemble()
+    {
+        $table = new Table();
+        $table->getAttributes()->set('class', 'common-table table-row-selectable');
+
+        $modalOpener = ['data-icinga-modal' => true, 'data-no-icinga-ajax' => true];
+
+        /** @var X509Schedule $schedule */
+        foreach ($this->schedules as $schedule) {
+            $row = Table::tr(null, $modalOpener);
```
Comment (lippserd) [inline library/X509/Widget/Schedules.php:40]: Why do we need the modal data attributes on both tr and td?

File: library/X509/Widget/Schedules.php [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+
+use Icinga\Module\X509\Common\Links;
+use Icinga\Module\X509\Model\X509Schedule;
+use ipl\Html\BaseHtmlElement;
+use ipl\Html\Table;
+use ipl\I18n\Translation;
+use ipl\Orm\Query;
+use ipl\Web\Widget\Link;
+
+class Schedules extends BaseHtmlElement
```
Comment (lippserd) [inline library/X509/Widget/Schedules.php:15]: Why does this not extend `Table` like `Jobs`?

File: public/css/module.less (hunk 3 above)
Comment (yhabteab) [reply public/css/module.less:10]: Nop! I have already reverted this change on my end!

File: library/X509/Widget/JobDetails.php [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+
+namespace Icinga\Module\X509\Widget;
+
+use Icinga\Module\X509\Model\X509JobRun;
+use ipl\Html\BaseHtmlElement;
+use ipl\Html\Table;
+use ipl\I18n\Translation;
+use ipl\Orm\Query;
+
+class JobDetails extends BaseHtmlElement
```
Comment (lippserd) [inline library/X509/Widget/JobDetails.php:13]: Why does this not extend Table?

File: library/X509/Widget/Schedules.php (hunk 4 above)
Comment (yhabteab) [reply library/X509/Widget/Schedules.php:40]: Not td, but `tr` and `a`. The `tr` tag is clickable when using a `table-row-selectable` class, and the name also contains the same link which redirects you to the same page as when you click the whole table row.

File: application/forms/Jobs/JobConfigForm.php [hunk 7]
```diff
@@ -0,0 +1,132 @@
...
+    }
+
+    protected function isUpdating(): bool
+    {
+        return Url::fromRequest()->getPath() === 'x509/job/update';
+    }
+
+    public function hasBeenSubmitted(): bool
+    {
+        $button = $this->getPressedSubmitElement()->getName();
```
Comment (lippserd) [inline application/forms/Jobs/JobConfigForm.php:41]: This can't work correctly as `getPressedSubmitElement()` may return `null`. Also the base class' method calls `hasBeenSent()` first for early exit which makes sense to keep.

File: application/forms/Jobs/JobConfigForm.php [hunk 8]
```diff
@@ -0,0 +1,132 @@
...
+    protected $job;
+
+    public function __construct(X509Job $job = null)
+    {
+        $this->job = $job;
+    }
+
+    protected function isUpdating(): bool
+    {
+        return Url::fromRequest()->getPath() === 'x509/job/update';
```
Comment (lippserd) [inline application/forms/Jobs/JobConfigForm.php:36]: Check for `$this->job !== null` instead?

File: application/forms/Jobs/JobConfigForm.php [hunk 9]
```diff
@@ -0,0 +1,132 @@
...
+    }
+
+    protected function assemble()
+    {
+        $this->addElement('text', 'name', [
+            'required'    => true,
+            'description' => t('Job name'),
+            'label'       => t('Name'),
+        ]);
+        $this->addElement('textarea', 'cidrs', [
```
Comment (lippserd) [inline application/forms/Jobs/JobConfigForm.php:52]: Either add newlines after `addElement()` everywhere or add none at all.

File: application/forms/Jobs/JobConfigForm.php [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+                Notification::success(t('Job removed'));
+            } catch (Exception $err) {
+                Notification::error(t('Failed to remove job') . ': ' . $err->getMessage());
+            }
+        } else {
+            $values = $this->getValues();
+
+            try {
+                if ($this->isUpdating()) {
+                    $message = t('Job updated');
```
Comment (lippserd) [inline application/forms/Jobs/JobConfigForm.php:115]: Please move message after the update.

File: application/forms/Jobs/JobConfigForm.php [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+                    $conn->update('x509_job', $values, ['id = ?' => $this->job->id]);
+                } else {
+                    $message = t('Job created');
```
Comment (lippserd) [inline application/forms/Jobs/JobConfigForm.php:118]: Same here: Move message after the insert and remove newline.

File: application/forms/Jobs/JobConfigForm.php [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+
+                Notification::success(t('Job removed'));
+            } catch (Exception $err) {
+                Notification::error(t('Failed to remove job') . ': ' . $err->getMessage());
+            }
+        } else {
+            $values = $this->getValues();
+
+            try {
+                if ($this->isUpdating()) {
```
Comment (lippserd) [inline application/forms/Jobs/JobConfigForm.php:114]: Logically, it would make sense to have the insert case first.

File: application/controllers/JobsController.php [hunk 13]
```diff
@@ -4,126 +4,71 @@
...
-    public function updateAction()
-    {
-        $name = $this->params->getRequired('name');
-        $form = $this->prepareForm();
-
-        $this->addTitleTab($this->translate('Update Job'));
-
-        $this->addContent($form);
-    }
+        $query = X509Job::on($this->getDb());
```
Comment (lippserd) [inline application/controllers/JobsController.php:25]: I would name it `$jobs` not `$query`.

File: application/controllers/JobsController.php [hunk 14]
```diff
@@ -4,126 +4,71 @@
...
-    {
-        $name = $this->params->getRequired('name');
-        $form = $this->prepareForm();
+        $sortControl = $this->createSortControl(
+            $query,
+            [
+                'name'   => $this->translate('Name'),
+                'author' => $this->translate('Author'),
+            ]
+        );
```
Comment (lippserd) [inline application/controllers/JobsController.php:45]:
```suggestion
        $sortControl = $this->createSortControl($jobs, [
            'name'   => $this->translate('Name'),
            'author' => $this->translate('Author')
        ]);
```

File: application/controllers/JobController.php [hunk 15]
```diff
@@ -0,0 +1,248 @@
...
+
+        $sortControl = $this->createSortControl(
+            $schedules,
+            [
+                'name'   => $this->translate('Name'),
+                'author' => $this->translate('Author'),
+                'ctime'  => $this->translate('Date Created'),
+                'mtime'  => $this->translate('Date Modified')
+            ]
+        );
```
Comment (lippserd) [inline application/controllers/JobController.php:127]:
```suggestion
        $sortControl = $this->createSortControl($schedules, [
            'name'   => $this->translate('Name'),
            'author' => $this->translate('Author'),
            'ctime'  => $this->translate('Date Created'),
            'mtime'  => $this->translate('Date Modified')
        ]);
```

File: application/controllers/JobController.php [hunk 16]
```diff
@@ -0,0 +1,248 @@
...
+            $jobRuns,
+            [
+                'schedule.name'    => $this->translate('Schedule Name'),
+                'schedule.author'  => $this->translate('Author'),
+                'total_targets'    => $this->translate('Total Targets'),
+                'finished_targets' => $this->translate('Finished Targets'),
+                'start_time desc'  => $this->translate('Started At'),
+                'end_time'         => $this->translate('Ended At')
+            ]
+        );
```
Comment (lippserd) [inline application/controllers/JobController.php:66]:
```suggestion
        $sortControl = $this->createSortControl($jobRuns, [
            'schedule.name'    => $this->translate('Schedule Name'),
            'schedule.author'  => $this->translate('Author'),
            'total_targets'    => $this->translate('Total Targets'),
            'finished_targets' => $this->translate('Finished Targets'),
            'start_time desc'  => $this->translate('Started At'),
            'end_time'         => $this->translate('Ended At')
        ]);
```

File: application/clicommands/JobsCommand.php [hunk 17]
```diff
@@ -27,11 +29,24 @@ class JobsCommand extends Command
...
+     *     icingacli x509 jobs run [OPTIONS]
+     *
+     * OPTIONS
+     *
+     * --job=<name>
+     *     Run all configured schedules only of the specified job.
+     *
+     * --schedule=<name>
+     *     Run only the given schedule within the specified job. Specifying a schedule name
+     *     without a job will be silently ignored and run all configured schedules of all jobs instead.
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:41]: I would exit with an error instead.

File: application/clicommands/JobsCommand.php [hunk 18]
```diff
@@ -53,13 +68,14 @@ public function runAction()
...
-        $watchdog = function () use (&$watchdog, $scheduler, &$scheduled, $parallel) {
-            $jobs = $this->fetchJobs();
+        $watchdog = function () use (&$watchdog, &$scheduled, $scheduler, $parallel) {
+            $jobs = $this->fetchSchedules();
             $outdatedJobs = array_diff_key($scheduled, $jobs);
             foreach ($outdatedJobs as $job) {
                 Logger::info(
-                    'Removing scheduled job %s, as it either no longer exists in the configuration or its config has'
-                    . ' been changed',
+                    'Removing scheduled %s from job %s, as it either no longer exists in the configuration or its'
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:76]: schedule~~d~~

File: library/X509/Job.php [hunk 19]
```diff
@@ -35,165 +37,212 @@
...
-     * @return $this
+     * @return array
      */
-    public function setFullScan(bool $fullScan): self
+    public function getExcludes(): array
     {
-        $this->fullScan = $fullScan;
-
-        return $this;
+        return $this->excludedTargets ?? [];
```
Comment (lippserd) [inline library/X509/Job.php:199]: Why don't you set `private $excludedTargets = []`?

File: library/X509/Job.php [hunk 20]
```diff
@@ -35,165 +37,212 @@
...
-     * Set since last scan threshold for the targets to rescan
+     * Set a set of IPs and host names to be excluded from scan
      *
-     * @param ?DateTime $dateTime
+     * @param string $targets
      *
      * @return $this
      */
-    public function setLastScan(?DateTime $dateTime): self
+    public function setExcludes(string $targets): self
```
Comment (lippserd) [inline library/X509/Job.php:209]: You could use `?string` to save `?? ''` when calling this method.

**Review by lippserd — CHANGES_REQUESTED** [review]
Here is the first set of requested changes. I'm not finished yet :).

Please also do the following:

* Use `translate()` instead of `t()` where appropriate.
* When setting tabs/controls/content in controllers I'd like to see the following flow:

```php
// Code for tabs
// Newline
// Code for controls
// Newline
// Code for content

File: application/forms/Jobs/ScheduleForm.php [hunk 21]
```diff
@@ -0,0 +1,179 @@
...
+     * @return array
+     */
+    public function getPartUpdates(): array
+    {
+        return $this->scheduleElement->prepareMultipartUpdate($this->getRequest());
+    }
+
+    public function hasBeenSubmitted(): bool
+    {
+        return $this->hasBeenSent() && ($this->getPopulatedValue('submit') || $this->getPopulatedValue('btn_remove'));
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply application/forms/Jobs/ScheduleForm.php:67]: `getPressedSubmitElement()` returns null in case of autosubmits, I just used `getPopulatedValue()` here instead of checking whether the pressed button is non-null and whether it matches one of these names.  `JobsConfigForm`, on the other hand, doesn't have any autosubmit elements, which is why I used the `getPressedSubmitElement()` function there.

File: application/clicommands/JobsCommand.php [hunk 22]
```diff
@@ -70,30 +91,21 @@ public function runAction()
...
-                        continue;
-                    }
+                $config = $job->getSchedule()->getConfig();
+                try {
+                    /** @var Frequency $type */
+                    $type = $config->type;
+                    $frequency = $type::fromJson($config->frequency);
+                } catch (Exception $err) {
+                    Logger::error(
+                        'Schedule %s from job %s has invalid schedule expression %s: %s',
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:101]: The message should be different, e.g. "Can't create schedule %s of job %s: %s"

File: application/clicommands/JobsCommand.php [hunk 23]
```diff
@@ -27,15 +30,32 @@ class JobsCommand extends Command
...
-     *   icingacli x509 jobs run
+     *     icingacli x509 jobs run [OPTIONS]
+     *
+     * OPTIONS
+     *
+     * --job=<name>
+     *     Run all configured schedules only of the specified job.
+     *
+     * --schedule=<name>
+     *     Run only the given schedule within the specified job. Specifying a schedule name
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:41]: of instead of within.

File: application/clicommands/JobsCommand.php [hunk 24]
```diff
@@ -27,15 +30,32 @@ class JobsCommand extends Command
...
+     *     without a job will fail immediately.
+     *
+     * --parallel=<number>
+     *     Allow scanning targets up to the specified number parallely (Default 256).
+     *     Might cause **too many open files error** if it's set to a higher number than the configured one.
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:46]:
```suggestion
     *     Allow parallel scanning of targets up to the specified number. Defaults to 256.
     *     May cause **too many open files** error if set to a number higher than the configured one (ulimit).
```

.

File: application/clicommands/JobsCommand.php [hunk 25]
```diff
@@ -108,28 +120,49 @@ public function runAction()
     }
 
     /**
-     * Fetch jobs from disk
+     * Fetch job schedules from database
      *
      * @return Job[]
      */
-    protected function fetchJobs(): array
+    protected function fetchSchedules(): array
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:127]: I would add parameters to not call `params->get()` every time this method is called.

File: application/clicommands/JobsCommand.php [hunk 26]
```diff
@@ -108,28 +120,49 @@ public function runAction()
...
+        $scheduleName = $this->params->get('schedule');
+        $jobs = X509Job::on($this->getDb());
+        if ($jobName) {
+            $jobs->filter(Filter::equal('name', $jobName));
+        }
+
+        $jobSchedules = [];
+        $snimap = SniHook::getAll();
+        foreach ($jobs as $jobConfig) {
+            $job = new Job($jobConfig->name, $jobConfig->cidrs, $jobConfig->ports, $snimap);
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:139]: Why not the following?

```
$job = (new ...)
    ->set()
    ->set();

File: application/clicommands/JobsCommand.php [hunk 27]
```diff
@@ -108,28 +120,49 @@ public function runAction()
...
+            }
 
-        $jobs = [];
-        foreach ($configs as $name => $config) {
-            if (! $config->get('schedule', $defaultSchedule)) {
-                Logger::debug('Job %s cannot be scheduled', $name);
+            $jobSchedules = [];
+            foreach ($schedules as $scheduleModel) {
+                $schedule = Schedule::fromModel($scheduleModel);
+                $job = clone $job;
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:153]: Why not the following?

```
$job = (clone ...)
    ->set()
    ->set();

File: application/clicommands/JobsCommand.php [hunk 28]
```diff
@@ -108,28 +120,49 @@ public function runAction()
...
+                $job->setUuid(Uuid::fromBytes($job->getChecksum()));
 
-                continue;
+                $jobSchedules[$job->getUuid()->toString()] = $job;
             }
 
-            $job = new Job($name, $config, SniHook::getAll());
-            $jobs[$job->getUuid()->toString()] = $job;
+            if (! isset($jobSchedules[$job->getUuid()->toString()])) {
+                Logger::info('Job %s does not provide any configured schedules. Skipping...', $jobConfig->getName());
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:161]:
```suggestion
                Logger::info('Skipping job %s because no schedules are configured', $jobConfig->getName());
```

File: application/clicommands/JobsCommand.php [hunk 29]
```diff
@@ -139,15 +172,24 @@ protected function fetchJobs(): array
...
+        $scheduler->on(Scheduler::ON_TASK_CANCEL, function (Job $task, array $_) {
+            Logger::info('Schedule %s from job %s canceled', $task->getSchedule()->getName(), $task->getName());
         });
 
-        $scheduler->on(Scheduler::ON_TASK_DONE, function (Task $job, $targets = 0) {
+        $scheduler->on(Scheduler::ON_TASK_DONE, function (Job $task, $targets = 0) {
             if ($targets === 0) {
-                Logger::warning('The job %s does not have any targets', $job->getName());
+                Logger::warning(
+                    'Schedule %s from job %s does not have any targets',
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:182]: of instead of from.

File: application/clicommands/JobsCommand.php [hunk 30]
```diff
@@ -139,15 +172,24 @@ protected function fetchJobs(): array
...
+                    $task->getSchedule()->getName(),
+                    $task->getName()
+                );
             } else {
-                Logger::info('Scanned %d target(s) from job %s', $targets, $job->getName());
+                Logger::info(
+                    'Scanned %d target(s) by schedule %s from job %s',
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:188]: of instead of from.

File: application/clicommands/JobsCommand.php [hunk 31]
```diff
@@ -139,15 +172,24 @@ protected function fetchJobs(): array
      */
     protected function attachJobsLogging(Scheduler $scheduler): void
     {
-        $scheduler->on(Scheduler::ON_TASK_CANCEL, function (Task $job, array $_) {
-            Logger::info('Job %s canceled', $job->getName());
+        $scheduler->on(Scheduler::ON_TASK_CANCEL, function (Job $task, array $_) {
+            Logger::info('Schedule %s from job %s canceled', $task->getSchedule()->getName(), $task->getName());
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:176]: of instead of from.

File: application/clicommands/JobsCommand.php [hunk 32]
```diff
@@ -160,21 +202,36 @@ protected function attachJobsLogging(Scheduler $scheduler): void
             }
         });
 
-        $scheduler->on(Scheduler::ON_TASK_FAILED, function (Task $job, Throwable $e) {
-            Logger::error('Failed to run job %s: %s', $job->getName(), $e->getMessage());
+        $scheduler->on(Scheduler::ON_TASK_FAILED, function (Job $task, Throwable $e) {
+            Logger::error(
+                'Failed to run schedule %s from job %s: %s',
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:207]: of instead of from.

File: application/clicommands/JobsCommand.php [hunk 33]
```diff
@@ -160,21 +202,36 @@ protected function attachJobsLogging(Scheduler $scheduler): void
...
+                $task->getName(),
+                $e->getMessage()
+            );
             Logger::debug($e->getTraceAsString());
         });
 
-        $scheduler->on(Scheduler::ON_TASK_RUN, function (Task $job, ExtendedPromiseInterface $_) {
-            Logger::info('Running job %s', $job->getName());
+        $scheduler->on(Scheduler::ON_TASK_RUN, function (Job $task, ExtendedPromiseInterface $_) {
+            Logger::info('Running schedule %s from job %s', $task->getSchedule()->getName(), $task->getName());
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:216]: of instead of from.

File: application/clicommands/JobsCommand.php [hunk 34]
```diff
@@ -160,21 +202,36 @@ protected function attachJobsLogging(Scheduler $scheduler): void
...
         });
 
-        $scheduler->on(Scheduler::ON_TASK_SCHEDULED, function (Task $job, DateTime $dateTime) {
-            Logger::info('Scheduling job %s to run at %s', $job->getName(), $dateTime->format('Y-m-d H:i:s'));
+        $scheduler->on(Scheduler::ON_TASK_SCHEDULED, function (Job $task, DateTime $dateTime) {
+            Logger::info(
+                'Scheduling %s from job %s to run at %s',
```
Comment (lippserd) [inline application/clicommands/JobsCommand.php:221]: of instead of from.

File: application/controllers/JobController.php [hunk 35]
```diff
@@ -0,0 +1,240 @@
...
+{
+    use Database;
+
+    /** @var X509Job */
+    protected $job;
+
+    public function init()
+    {
+        parent::init();
+        $this->getTabs()->disableLegacyExtensions();
```
Comment (lippserd) [inline application/controllers/JobController.php:36]: Add newline before please.

**Review by lippserd — CHANGES_REQUESTED** [review]
I talked to @theFeu about the semantics of "of vs. from job" and we both prefer of instead of from, except when something is removed from a job.

**Review by lippserd — APPROVED** [review]

**Comment by yhabteab** [comment]
## Blocked by

- https://github.com/Icinga/ipl-web/pull/183

File: library/X509/Widget/Schedules.php [hunk 36]
```diff
@@ -0,0 +1,63 @@
...
+use ipl\I18n\Translation;
+use ipl\Orm\Query;
+use ipl\Web\Widget\EmptyState;
+use ipl\Web\Widget\Link;
+
+class Schedules extends Table
+{
+    use Translation;
+
+    /** @var array<string, mixed> */
```
Comment (lippserd) [inline library/X509/Widget/Schedules.php:19]: Please remove the comment. The base class should provide the proper type.

File: library/X509/Widget/Jobs.php [hunk 37]
```diff
@@ -0,0 +1,61 @@
...
+use ipl\Web\Widget\Link;
+
+class Jobs extends Table
+{
+    use Translation;
+
+    /** @var Query */
+    protected $jobs;
+
+    /** @var array<string, mixed> */
```
Comment (lippserd) [inline library/X509/Widget/Jobs.php:21]: Please remove the comment. The base class should provide the proper type.

**Review by lippserd — CHANGES_REQUESTED** [review]

File: application/clicommands/JobsCommand.php [hunk 38]
```diff
@@ -139,15 +184,24 @@ protected function fetchJobs(): array
...
-            Logger::info('Job %s canceled', $job->getName());
+        $scheduler->on(Scheduler::ON_TASK_CANCEL, function (Job $task, array $_) {
+            Logger::info('Schedule %s of job %s canceled', $task->getSchedule()->getName(), $task->getName());
         });
 
-        $scheduler->on(Scheduler::ON_TASK_DONE, function (Task $job, $targets = 0) {
+        $scheduler->on(Scheduler::ON_TASK_DONE, function (Job $task, $targets = 0) {
             if ($targets === 0) {
-                Logger::warning('The job %s does not have any targets', $job->getName());
+                Logger::warning(
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply application/clicommands/JobsCommand.php:193]: Yes!

File: public/css/module.less [hunk 39]
```diff
@@ -6,6 +6,18 @@
 @cert-segment-color-3: #1982C4;
 @cert-segment-color-4: #6A4C93;
 
+.empty-state {
```
Comment (lippserd) [inline public/css/module.less:9]: Is this still necessary?

File: doc/03-Configuration.md [hunk 40]
```diff
@@ -34,17 +29,37 @@ port:
 
 `443,5665-5669`
 
-Scan jobs can be executed using the `icingacli x509 scan` CLI command. The `--job` option is used to specify the scan
-job which should be run:
+Additionally, each job may also exclude specific **hosts** and **IP** addresses from scan. These hosts won't be scanned
+when you run the [scan](04-Scanning.md#scan-command) or [jobs](04-Scanning.md#scheduling-jobs) command. Excluding an
+entire network and specifying IP addresses in CIDR format will not work. You must specify a comma-separated concrete
```
Comment (lippserd) [inline doc/03-Configuration.md:34]: The last sentence reads like some words are missing.

File: doc/03-Configuration.md [hunk 41]
```diff
@@ -34,17 +29,37 @@ port:
...
+**IP** and **host CN**, e.g:
 
-```
-icingacli x509 scan --job lan
-```
+`192.0.2.2,192.0.2.5,icinga.com`
+
+### Job Schedules
+
+Schedules are `cron` and [rrule](https://www.rfc-editor.org/rfc/rfc5545) based configs used to run periodically
```
Comment (lippserd) [inline doc/03-Configuration.md:41]: used to run **jobs**

File: doc/03-Configuration.md [hunk 42]
```diff
@@ -34,17 +29,37 @@ port:
...
+at the given interval. Every job is allowed to have multiple schedules that can be run independently of each other.
+Don't worry, you don't need to know anything about rrule to create **rrule** based schedules. All you need to do is
```
Comment (lippserd) [inline doc/03-Configuration.md:43]: Why mention **rrule** at all? Is that shown somewhere in the frontend? I would speak of "repeat patterns", "rule based", or something like that.

File: doc/03-Configuration.md [hunk 43]
```diff
@@ -34,17 +29,37 @@ port:
...
+
+A schedule that runs weekly on **Friday** and scans all targets that have not yet been scanned, or
+whose last scan is older than `1 week`.
+
+![Weekly Schedules](res/weekly-schedules.png "Weekly Schedules")
+
+
+##### Cron Schedules
+
+The `cron` format is as follows:
```
Comment (lippserd) [inline doc/03-Configuration.md:62]: I know we had that before but I would remove cron doc here and link to some external page.

File: doc/04-Scanning.md [hunk 44]
```diff
@@ -0,0 +1,85 @@
+# <a id="Scanning"></a>Scanning
+
+The Icinga Certificate Monitoring provides CLI commands to scan arbitrary **hosts** and **IPs** in various ways.
```
Comment (lippserd) [inline doc/04-Scanning.md:3]: Why arbitrary? Hosts and IPs have to be configured. I don't think that's arbitrary.

File: doc/04-Scanning.md [hunk 45]
```diff
@@ -0,0 +1,85 @@
...
+These commands are listed below and can be used individually. It is necessary for all commands to know which IP address
+ranges and ports to scan. These can be configured as described [here](03-Configuration.md#configure-jobs).
+
+## Scan Command
+
+The scan command, as its name implies, scans targets to find their X.509 certificates and track changes to them.
```
Comment (lippserd) [inline doc/04-Scanning.md:9]: Remove `as its name implies`.

File: application/forms/Jobs/ScheduleForm.php [hunk 46]
```diff
@@ -0,0 +1,201 @@
...
+
+    /**
+     * Get multipart updates
+     *
+     * @return array<int, BaseHtmlElement>
+     */
+    public function getPartUpdates(): array
+    {
+        /** @var RequestInterface $request */
+        $request = $this->getRequest();
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply application/forms/Jobs/ScheduleForm.php:71]: Yep!

File: public/css/module.less (hunk 39 above)
Comment (yhabteab) [reply public/css/module.less:9]: Yes! The empty state default styles apply only when it's within an `item-list/list-item` classes.

File: library/X509/Common/JobUtils.php [hunk 47]
```diff
@@ -6,91 +6,109 @@
...
      * @return $this
      */
-    public function setConfig(ConfigObject $jobConfig): self
+    public function setCIDRs(string $cidrs): self
     {
-        $this->config = $jobConfig;
+        foreach (Str::trimSplit($cidrs) as $cidr) {
+            $pieces = Str::trimSplit($cidr, '/');
+            if (count($pieces) !== 2) {
+                Logger::warning('CIDR %s is in the wrong format', $cidr);
```
[the remark this answers is not in the document]
Comment (yhabteab) [reply library/X509/Common/JobUtils.php:44]: If I have to move this back to the `Job` class, this won't be testable.

File: public/css/module.less (hunk 39 above)
Comment (lippserd) [reply public/css/module.less:9]: Ok, why? I don't think that restriction makes sense.

File: application/forms/Jobs/JobConfigForm.php [hunk 48]
```diff
@@ -0,0 +1,155 @@
...
+ * Create, update and delete jobs
+ */
+class JobConfigForm extends CompatForm
+{
+    use Database;
+
+    /** @var ?X509Job */
+    protected $job;
+
+    public function __construct(X509Job $job = null)
```
[the remark this answers is not in the document]
Comment (lippserd) [reply application/forms/Jobs/JobConfigForm.php:31]: True.

File: application/clicommands/JobsCommand.php (hunk 38 above)
[the remark this answers is not in the document]
Comment (lippserd) [reply application/clicommands/JobsCommand.php:187]: In my opinion, there is a difference in severity between a job that does not yield any target and a job that does not yet rescan **existing** targets. Are we able to distinguish this and log it accordingly?

File: public/css/module.less (hunk 39 above)
Comment (yhabteab) [reply public/css/module.less:9]: The empty state class is also used in the host/service object detail view, for example, and there it is styled differently than when it is within an item-list. Thus, the emty-state is styled differently depending on where it is used, so we can't apply the `item-list` styles globally.

Comment (lippserd) [reply public/css/module.less:9]: Sure, but I meant that you are basically copying the styles since the views here are list/main views but use tables instead of being item lists. I can't reuse the styles for the empty state (for lists/main views) if I want to, but that should be possible.

File: doc/03-Configuration.md [hunk 49]
```diff
@@ -34,65 +29,24 @@ port:
...
-Run once an hour at the beginning of the hour               | 0 * * * *
-
-Jobs are executed on CLI with the `jobs` command:
-
-```
-icingacli x509 jobs run
-```
+Additionally, each job may also exclude specific **hosts** and **IP** addresses from scan. These hosts won't be scanned
+when you run the [scan](04-Scanning.md#scan-command) or [jobs](04-Scanning.md#scheduling-jobs) command. Excluding an entire network and specifying IP addresses in CIDR
+format will not work. You must specify concrete **IP** and **host CN** separated with commas, e.g:
```
Comment (lippserd) [inline doc/03-Configuration.md:34]: Shouldn't this read `You must specify concrete **IP**s or **host CN**s separated with commas`?

File: library/X509/Common/JobUtils.php (hunk 47 above)
[the remark this answers is not in the document]
Comment (lippserd) [reply library/X509/Common/JobUtils.php:44]: When constructing a `Job` the `CIDRs` should already be parsed. Setters must not log.

**Review by lippserd — CHANGES_REQUESTED** [review]

File: public/css/module.less (hunk 39 above)
Comment (nilmerg) [reply public/css/module.less:9]: There's `EmptyStateBar` now for the style which can be used on its own without a item list or item table. The margin however is related to the placement, this must be kept here but should be applied only to the tables where required.

File: library/X509/Widget/JobDetails.php [hunk 50]
```diff
@@ -0,0 +1,60 @@
...
+                static::td((string) $run->finished_targets),
+                static::td($run->start_time->format('Y-m-d H:i')),
+                static::td($run->end_time ? $run->end_time->format('Y-m-d H:i') : 'N/A')
+            );
+
+            $this->addHtml($row);
+        }
+
+        if ($this->isEmpty()) {
+            $this->addHtml(new EmptyState($this->translate('Job never run.')));
```
Comment (nilmerg) [inline library/X509/Widget/JobDetails.php:45]: `$this` is a `table`, the empty state (bar) a `div`, and a `div` isn't valid inside a `table`. That's why ipl-web transforms an item list/table to a `div` if it's adding the bar, you should do the same. (And everywhere else where you're using this)

File: public/css/module.less (hunk 39 above)
Comment (lippserd) [reply public/css/module.less:9]: > There's `EmptyStateBar` now for the style which can be used on its own without a item list or item table. The margin however is related to the placement, this must be kept here but should be applied only to the tables where required.

Nice!

**Review by lippserd — APPROVED** [review]

**Comment by yhabteab** [comment]
@lippserd please check the latest 2 commits again.

**Review by lippserd — APPROVED** [review]

**Comment by yhabteab** [comment]
Just rebased!
