### PR TITLE
Fix integer overflow and log total IPs to be scanned within a CIDR

### LINKED ISSUE #110: Error scanning IPv6 networks
## Describe the bug
If an IPv6 network is to be scanned, the scan returns the error "The job 'xxx' does not have any targets".

## To Reproduce
In Icingaweb2 go to Configuration -> Modules -> x509 -> Jobs and enter

* Job Name: lan-ipv6
* CIDRs: ::/64
* Ports: 443
* Runtime: 0 0 * * *

Execute the scan job

`icingacli x509 scan --job lan-ipv6 --debug`

Result:
`The job 'lan-ipv6' does not have any targets.`

## Expected behavior
Scan the /64 IPv6 network

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):

```
Icinga Web 2 Version 	2.10.1
Git commit 	974729a6421c17fdb8bb1931623107cf6a90fc7e
PHP Version 	7.3.29
Git commit date 	2022-04-06

Loaded Libraries
icinga/icinga-php-library 	0.8.1
icinga/icinga-php-thirdparty 	0.10.0

Loaded Modules
businessprocess 		2.4.0
director 		1.9.1
doc 		2.10.1
fileshipper 		1.2.0
global-dashboards 		0.0.0
grafana 		1.4.2
graphite 		1.2.0
idoreports 		0.10.0
incubator 		0.16.0
ipl 		v0.5.0
monitoring 		2.10.1
pdfexport 		0.10.1
reactbundle 		0.7.0
reporting 		0.10.0
vspheredb 		1.4.0
x509 		1.1.2
```

* Web browser used:

Firefox 91.10.0esr (32-Bit)

* Icinga 2 version used (`icinga2 --version`):

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.3-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1160.66.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```

* PHP version used (`php --version`):

7.3.29

* Server operating system and version:

CentOS 7.9

### PR DESCRIPTION
**Pull request by yhabteab**
Currently the number of IP addresses to be scanned is computed by bit shifting, this can very quickly lead to integer overflow on fairly large networks ( is only the case with IPV6). This PR fixes this by calculating the number of addresses with `2^n` using the `pow()` function, because this will be automatically cast to double if the result can' t be stored in an integer type.

fixes #110

### CODE REVIEW

File: library/X509/Job.php [hunk 1]
```diff
@@ -99,9 +99,10 @@ private static function generateTargets(ConfigObject $jobDescription, array $hos
 //            }
             $ipv6 = filter_var($start_ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false;
             $subnet = $ipv6 ? 128 : 32;
-            $ip_count = 1 << ($subnet - $prefix);
+            $ip_count = pow(2, ($subnet - $prefix) - 2);
             $start = static::addrToNumber($start_ip);
-            for ($i = 0; $i < $ip_count; $i++) {
+            $scanLimit = $jobDescription->get('scan_limit', pow(2, 327831396));
```
Comment (nilmerg) [inline library/X509/Job.php:104]: > php > echo pow(2, 327831396);
> INF

:thinking: :rofl:

Comment (yhabteab) [reply library/X509/Job.php:104]: Should actually match this value 🙈 `7.391.088.000`

**Review by lippserd — CHANGES_REQUESTED** [review]
I would not limit the IPs to be scanned in this way. There is no indication anywhere that this is happening, and there may be IPs that are never scanned since we don't have partial updates (yet). I would add a log message indicating how many total IPs are to be scanned, but that's about it.

File: library/X509/Job.php [hunk 2]
```diff
@@ -99,7 +99,10 @@ private static function generateTargets(ConfigObject $jobDescription, array $hos
 //            }
             $ipv6 = filter_var($start_ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false;
             $subnet = $ipv6 ? 128 : 32;
-            $ip_count = 1 << ($subnet - $prefix);
+            $ip_count = pow(2, ($subnet - $prefix) - 2);
+
+            Logger::info("Found a total of '%d' IPs in CIDR '%s' to be scanned.", $ip_count, $cidr);
```
Comment (lippserd) [inline library/X509/Job.php:104]: Just use `Scanning '%d' IPs in the CIDR '%s'`. It's short and tells you exactly what the daemon will do.

**Review by lippserd — CHANGES_REQUESTED** [review]

File: library/X509/Job.php [hunk 3]
```diff
@@ -101,7 +101,10 @@ private static function generateTargets(ConfigObject $jobDescription, array $hos
 //            }
             $ipv6 = filter_var($start_ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false;
             $subnet = $ipv6 ? 128 : 32;
-            $ip_count = 1 << ($subnet - $prefix);
+            $ip_count = pow(2, ($subnet - $prefix) - 2);
```
Comment (lippserd) [inline library/X509/Job.php:104]: Use `$numIps` or something like that. Not snake_case at least 😉.

File: library/X509/Job.php [hunk 4]
```diff
@@ -101,7 +101,10 @@ private static function generateTargets(ConfigObject $jobDescription, array $hos
...
+
+            Logger::info("Scanning '%d' IPs in the CIDR '%s'.", $ip_count, $cidr);
```
Comment (lippserd) [inline library/X509/Job.php:106]: Just `%d` instead of `'%d'`.

**Review by lippserd — CHANGES_REQUESTED** [review]
Sorry, missed some things in the last review.

File: library/X509/Job.php [hunk 5]
```diff
@@ -101,9 +101,12 @@ private static function generateTargets(ConfigObject $jobDescription, array $hos
 //            }
             $ipv6 = filter_var($start_ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false;
             $subnet = $ipv6 ? 128 : 32;
-            $ip_count = 1 << ($subnet - $prefix);
+            $numIps = pow(2, ($subnet - $prefix) - 2);
+
+            Logger::info("Scanning %d IPs in the CIDR '%s'.", $numIps, $cidr);
```
Comment (lippserd) [inline library/X509/Job.php:106]: I also think it makes sense to remove the other quotes.

**Review by lippserd — CHANGES_REQUESTED** [review]

**Review by lippserd — APPROVED** [review]
