### PR TITLE
Enhance certificate verification process

### LINKED ISSUE #175: The scan creates many temp files and doesn't end
## Describe the bug
When a scan job is launched, automatically via cron job or manually, I noticed many file created on a subfolder inside /tmp, that contains files with prefix intermediateXXXXXXXX or certXXXXXXX.
The task doesn't not complete and I need to kill it to avoid filling the disk space.

## To Reproduce
1. Launch a scan job via icingacli or via cron job
2. Look at /tmp/xxxxxxxxxxxxx to see the temporary files created, some of them with 20+ mb of size
3. The task doesn't complete and I need to kill the pid

## Expected behavior
The scan task ends with no problems from many temp files

## Screenshots
image
image

## Your Environment
* Icinga Web 2 version and modules (System - About): Icingaweb2 v2.11.1, Icinga X509 v1.2.1
* Icinga 2 version used (`icinga2 --version`): 2.13.5
* PHP version used (`php --version`): 7.3.31
* Server operating system and version: Debian 10.12

### PR DESCRIPTION
**Pull request by yhabteab**
This PR reduces the number of database queries performed per certificate chain to a single query and allocates **temp** file storage per certificate chain (this makes it possible to free all storage files after each iteration, which should prevent the disk from being crowded when there are a large number of certificate chains to verify).

fixes #175

### CODE REVIEW

File: library/X509/CertificateUtils.php [hunk 1]
```diff
@@ -504,18 +496,28 @@ public static function verifyCertificates(Connection $db)
...
                 // TODO: https://github.com/Icinga/ipl-orm/pull/78
-                $db->update(
-                    'x509_certificate_chain',
-                    $set,
-                    ['id = ?' => $chain->id]
-                );
+                $db->update('x509_certificate_chain', $set, ['id = ?' => $chainId]);
+            };
+
+            foreach ($certs as $cert) {
```
Comment (lippserd) [inline library/X509/CertificateUtils.php:509]: I'd like to make this a library function, e.g.

```
/**
 * Yield sets of items from an iterator grouped by a specific criterion gathered from a callback
 *
 * @param Iterator $iterator
 * @param callable $groupBy
 *
 * @return Generator
 */
function yield_groups(Iterator $iterator, callable $groupBy): Generator
{
    if (! $iterator->valid()) {
        return;
    }

    $attribute = $groupBy($iterator->current(), $iterator->key());
    $group = [$iterator->current()];
//    $group = [$iterator->key() => $iterator->current()];

    $iterator->next();
    for (; $iterator->valid(); $iterator->next()) {
        $a = $groupBy($iterator->current(), $iterator->key());
        if ($a !== $attribute) {
            yield $attribute => $group;

            $group = [];
            $attribute = $a;
        }
        
        $group[] = $iterator->current();
//        $group[$iterator->key()] = $iterator->current();
    }

    if (! empty($group)) {
        yield $attribute => $group;
    }
}
```

What do you think? And @nilmerg what do you think?

**Review by lippserd — CHANGES_REQUESTED** [review]

File: library/X509/CertificateUtils.php (hunk 1 above)
Comment (yhabteab) [reply library/X509/CertificateUtils.php:509]: When the values to be grouped, i.e. `$group[] = $iterator->current()` could also be specified by a callback, it would work. Such a grouping function would also be used for Sla queries in Icinga DB Web.

Comment (nilmerg) [reply library/X509/CertificateUtils.php:509]: Sure. Though, why not foreach?

**Review by lippserd — APPROVED** [review]

**Comment by yhabteab** [comment]
## Blocked by

- https://github.com/Icinga/ipl-stdlib/pull/46
